vim.single2<-function(primes,mat.eval,cl,with.nplus=TRUE){
	n.col<-ncol(mat.eval)
	mat.in<-matrix(0,n.col,n.col)
	id.primes<-colnames(mat.eval)%in%primes
	n.primes<-length(primes)
	mat.in[id.primes,id.primes]<-1-diag(n.primes)
	mat.in[!id.primes,!id.primes]<-diag(n.col-n.primes)
	mat.in[id.primes,!id.primes]<-1
	mat.pred<-mat.eval%*%mat.in
	mat.pred[mat.pred>1]<-1
	vec.improve<-colSums(mat.pred==cl)
	preds<-rowSums(mat.eval[,id.primes,drop=FALSE])>0
	n.corr<-sum(preds==cl)
	if(with.nplus)
		vec.improve<-ifelse(id.primes,n.corr-vec.improve,vec.improve-n.corr)
	else
		vec.improve<-ifelse(id.primes,n.corr-vec.improve,0)
	names(vec.improve)<-colnames(mat.eval)
	vec.improve
}

